import { Routes } from '@angular/router';
import { HomeComponent } from './home.component';
import { LoginComponent } from './login.component';
import { RegisterComponent } from './register.component';
import { ProfileComponent } from './profile.component';
import { BookingsComponent } from './bookings.component';
import { BookingRequestsComponent } from './booking-requests.component';
import { ChatComponent } from './chat.component';
import { DebugChatComponent } from './debug-chat.component';
import { ListingDetailComponent } from './listing-detail.component';
import { PetProfileComponent } from './pet-profile.component';
import { SitterProfileComponent } from './sitter-profile.component';
import { ContactComponent } from './contact.component';
import { RatingComponent } from './rating.component';

export const routes: Routes = [
  { path: '', component: HomeComponent },
  { path: 'login', component: LoginComponent },
  { path: 'register', component: RegisterComponent },
  { path: 'profile', component: ProfileComponent },
  { path: 'bookings', component: BookingsComponent },
  { path: 'booking-requests', component: BookingRequestsComponent },
  { path: 'chat/:id', component: ChatComponent },
  { path: 'debug-chat', component: DebugChatComponent },
  { path: 'listing/:id', component: ListingDetailComponent },
  { path: 'pet-profile', component: PetProfileComponent },
  { path: 'pet/:id', component: PetProfileComponent },
  { path: 'sitter-profile', component: SitterProfileComponent },
  { path: 'sitter/:id', component: SitterProfileComponent },
  { path: 'contact', component: ContactComponent },
  { path: 'rating/:bookingId', component: RatingComponent },
];
